[package]
authors = ["Byron Batteson"]
description = "A thread pool implementation for educational purposes"
license = "MIT"
edition = "2021"
name = "wadingpool"
version = "0.1.0"

[dev-dependencies]
rand = "0.8.5"
tracing-subscriber = "0.3.18"

[dependencies]
tracing = "0.1.40"
